-- MySQL Script generated by MySQL Workbench
-- Sat 03 Jun 2017 03:47:05 AM CLT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`debug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`debug` (
  `phone_number` DECIMAL(10,0) NOT NULL,
  `user` VARCHAR(45) NOT NULL DEFAULT 'ADMIN',
  PRIMARY KEY (`phone_number`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`debug`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`debug` (`phone_number`, `user`) VALUES ('+56983746523', '');
INSERT INTO `mydb`.`debug` (`phone_number`, `user`) VALUES ('+56988473901', DEFAULT);
INSERT INTO `mydb`.`debug` (`phone_number`, `user`) VALUES ('+56982736594', DEFAULT);
INSERT INTO `mydb`.`debug` (`phone_number`, `user`) VALUES ('+56984793970', DEFAULT);
INSERT INTO `mydb`.`debug` (`phone_number`, `user`) VALUES ('+56988112347', DEFAULT);
INSERT INTO `mydb`.`debug` (`phone_number`, `user`) VALUES ('+56988901927', DEFAULT);
INSERT INTO `mydb`.`debug` (`phone_number`, `user`) VALUES ('+56981956354', DEFAULT);

COMMIT;

